user_name = input("Enter your name: ")
print(type(user_name))
user_surname = input("Enter your surname: ")
print(type(user_surname))
user_age = input("Enter your age: ")
user_age = int(user_age)
print(type(user_age))
user_hight = input(user_hight)
user_hight = float(user_hight)
print(type(user_hight))
user_marital_status = input("Are you marred?:")
user_marital_status = bool(user_marital_status)
print(type(user_marital_status))
number_of_childre = input("Enter number of your children: ")
number_of_children = bool(number_of_children)
print(type(number_of_children))
print("Name: " + user_name, "Surname: " + user_surname, "Age: " + user_age, "Hight: " + user_hight, "Marred: " + user_marital_status, "Number of children: "+ number_of_children)