user_name = input("Enter your name: ")
print(user_name)
print(type(user_name))
user_surname = input("Enter your surname: ")
print(user_surname)
print(type(user_surname))
user_age = input("Enter your age: ")
user_age = int(user_age)
print(user_age)
print(type(user_age))